print("Naima Here!Day 2 Assignment 1 on String ")
a = "Naima is a Software Developer"
b = " Naima is a Writer"
print(a + " "+ b)
print(a.split())
print(a.lower())
print(b.Istrip(Naima))
print(a.replace("Naima","Waheda"))
print(b.upper())
print("Naima Here!Day 2 Assignment 2 on List")
lst = ['Naima', 1, 6 , 'hello',3 , 'one']
print(lst)
print(lst.sort())
print(lst.append('hello'))
print(lst.count(3))
print(lst.remove("one"))
print(lst.clear())

print("Naima Here!Day 2 Assignment 3 on Dictionary ") 
car = { "brand": "Nano" , "model":"YelloCar" , "yearOfSale": 2020}
x = (car.get("model"))
print(x)
y = car.keys()
print(y)
car.pop("model")
print(car)
z = car.values()
print(z)
car.update({"price":1000000})
print(car)
w = car.copy()
print(w)
car.clear()
print(car)
